Repository mmkal/expect-type, pull requests merged in 2024-08, with the labels that each got.

#91 Fix minor issues in docs
  README.md
  src/index.ts
  test/ts-output.ts
  test/types.test.ts
  test/usage.test.ts
Labels: documentation

#94 Update `pnpm` to version 9.7.0
  package.json
Labels: chore

#83 improve overloads support, attempt 2
  README.md
  src/branding.ts
  src/index.ts
  src/overloads.ts
  src/utils.ts
  test/__snapshots__/errors.test.ts.snap
  test/types.test.ts
  test/usage.test.ts
Labels: New feature, Breaking Change

#99 Remove unused disable directives for ESLint
  src/index.ts
  test/types.test.ts
  test/usage.test.ts
Labels: chore

#100 JSDoc improvements
  src/index.ts
  src/messages.ts
  src/overloads.ts
  src/utils.ts
Labels: documentation, chore

#107 Re-export everything in `overloads.ts` file
  src/index.ts
Labels: chore

#104 Mark internal APIs with `@internal` JSDoc tag
  src/index.ts
  src/messages.ts
  src/overloads.ts
  src/utils.ts
Labels: documentation, chore

#108 Add `are-the-types-wrong` CI job
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
Labels: CI
