Repository mmkal/expect-type, pull requests merged in 2025-02, with the labels that each got.

#134 chore: add TypeScript 5.6 and 5.7 to testing matrix
  .github/workflows/ci.yml
Labels: CI, chore

#142 ci: fix `html` reporter in CI
  .github/workflows/ci.yml
Labels: CI

#98 .map fn
  README.md
  src/index.ts
  test/usage.test.ts
Labels: New feature
